### ISSUE TITLE
Could not open db.json

### ISSUE THREAD

**Issue by teffy** [tea3/hexo-include-markdown#2]
```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Linux 4.10.0-42-generic linux x64
http_parser: 2.7.0
node: 9.2.0
v8: 6.2.414.44-node.11
uv: 1.16.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```
```
Error log:
FATAL [hexo-include-markdown] Could not open db.json .
Error: [hexo-include-markdown] Could not open db.json .
    at ReadFileContext.fs.readFile [as callback] (/home/lumeng/Workspace/blog/test/teffy.github.io/node_modules/hexo-include-markdown/lib/orverwriteCache.js:22:15)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
```
When I want to use markdown include plugin yesterday, I installed the plugin an enable it in my old workspace,there is the db.json file,it worked well.
But I got this error when I changed a workspace to write blog with github + hexo, it's a new workspace,just contains the hexo environment.
```
npm install hexo --save 
npm install hexo-include-markdown --save
```

**Comment by tea3** [comment]
@teffy 
It seems that db.json may be broken while using the plugin. Could you inititalize db.json  the follow as ?

1. Delete `db.json` , if exists db.json.
2. Create `db.json`.
3. Please enter the command `$ hexo clean`.
4. Finaly , Please enter the command `$ hexo s` .

**Comment by teffy** [comment]
Thank you.
It works well now by 
```
touch db.json
```
in the new workspace.
There is no db.json file in the new workspace.Maybe you can check the existence of db.json,then create it when there is no db.json file just  like my case.
