### ISSUE TITLE
Refer to layout

### ISSUE THREAD

**Issue by ghost** [tea3/hexo-include-markdown#3]
For this file `source/_ template/template.md` ...

How can I make it work with reference to another `layout` for example `layout: post`?

So...

`template.md`:

```
---
layout: post
title: Hola amigos
photos: http://pic.jpg
author: John
date: 10-03-2018
---
```

And my `layout: post` is a normal `html / ejs` file like this...

```
<div class="author"><%- post.author %></div>
<div class="date"><%- post.date %></div>
```

etc.

How to make it work with a `layout` reference?

**Comment by tea3** [comment]
@rabas007 
Sorry, it's very difficult. Because `template.md` is read as a pure markdown file.
Is this plugin useful ?
https://github.com/kulikala/hexo-helper-partial-page

**Comment by ghost** [comment]
@tea3 - Thanks... unfortunately not. I will play around with it a bit.
