### ISSUE TITLE
Netlifyで[hexo-include-markdown] Could not open db.json .というエラー

### ISSUE THREAD

**Issue by kohki-shikata** [tea3/hexo-include-markdown#4]
他のプラグインやナレッジも含めありがたく使わせてもらっています。いつもありがとうございます。

さて、掲題の通りのエラーです。
Netlifyは、tea3さんのやり方とは違い、NetlifyのCIを使ってデプロイしています。

ローカルでは問題なく表示されました。`hexo s`または`hexo d`で正常に表示または書き出されています。

db.jsonが怪しいと思い、db.jsonを削除すると、NetlifyCI上のコンソールと同じエラーが出ました。

先にdb.jsonが生成されていないといけないと思うのですが、db.jsonがない場合、エラーですべてが止まってしまいます。

こちらでも回避できる術がないかロジックを見てみたいと思いますが、何か思い当たる節がありましたら、ご共有いただけないでしょうか。

よろしくお願いします。

> hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

**Comment by tea3** [comment]
プラグインやサイトの方も参考にしていただきありがとうございます。
ご質問の内容ですが、稀にdb.jsonのデータが破損することがあるようです。

具体的にはJSONファイルが`{}`で閉じられないような現象を確認しています。

NetlifyCIの場合は、

1. 空の`db.json`を生成
2. `hexo clean`コマンドを走らせる

といった動作をCIに追加する事は可能でしょうか？取り急ぎで恐れ入りますが、ご検討をお願いします。

**Comment by kohki-shikata** [comment]
早速のご回答ありがとうございます。
後ほど検証してみますね！

**Comment by kohki-shikata** [comment]
`touch db.json && hexo generate`で、無事うまく生成されました！
ありがとうございます。
取り急ぎ、ご報告まで。

**Comment by tea3** [comment]
@kohki-shikata 
無事ページが生成されたようで良かったです^^
