### ISSUE TITLE
Import in markdown table

### ISSUE THREAD

**Issue by Ovilia** [tea3/hexo-include-markdown#5]
## For BUG

- BUG description

When import inside a markdown table:

```text
|A|B|
|-|-|
|a1|<!-- md _x.md -->|
```

In `_x.md`, text is defined as `b1`.

But there is an extra `<tr>` line in the table result.

```html
...
<tr>
  <td>a1</td>
  <td>b1</td>
</tr>
<tr>
  <td></td>
</tr>
```

How to remove the extra `<tr>` line?

- the way to reproduce
- log with hexo

## For question

just push question

## For feature request

just push feature request

## Environment Info

OS version

- OSX (please tell me version)
- Windows (please tell me version)
- Linux (please tell me version)

Node version(`node -v`)
```
v8.1.2
```

Your site `_config.yml`
```
# Hexo Configuration
...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.2
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

**Comment by tea3** [comment]
@Ovilia 

Thank you for using this plugin. Sorry , I could not reproduce the problem you presented. I'm using node.js v8.4 and using [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape). Which theme do you use ? Does the same problem occur even if I change the theme ? Please check these case.

![ss](https://user-images.githubusercontent.com/15667928/44759982-b7541900-ab77-11e8-8cef-e98f29d82ff9.jpg)
![ss2](https://user-images.githubusercontent.com/15667928/44759985-bae7a000-ab77-11e8-91b6-e0f04facf43b.jpg)

**Comment by Ovilia** [comment]
I'm using a custom theme writing by myself, in which `<%- page.content %>` is used for markdown part. Is it right?

**Comment by tea3** [comment]
It's right.  Please temporarily switch to a different theme (e.g. [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape)) and check.
